name: run-tests-doctum

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        laravel: [10]
        stability: [prefer-dist]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
        - uses: actions/checkout@v4

        - name: build doctum docs
          uses: sudo-bot/action-doctum@v5
          with:
              config-file: doctum-config.php
              # parse, render or update
              method: "update"
              # (optional) defaults to '--output-format=github --no-ansi --no-progress -v'
              cli-args: "--output-format=github --no-ansi --no-progress -v"
      
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
            commit_message: Automated Change
        
            # Optional. Local and remote branch name where commit is going to be pushed
            #  to. Defaults to the current branch.
            #  You might need to set `create_branch: true` if the branch does not exist.
            branch: doctum-docs-new
        
            # Optional. Options used by `git-commit`.
            # See https://git-scm.com/docs/git-commit#_options
            commit_options: '--no-verify --signoff'
                
            # Optional. Options used by `git-push`.
            # See https://git-scm.com/docs/git-push#_options
            push_options: '--force'

            # Optional. Local file path to the repository.
            # Defaults to the root of the repository.
            repository: .
        
            # Optional commit user and author settings
            commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
            commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
            commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
            create_branch: true