name: build-doctum-docs

on: 
    # Runs on pushes targeting the default branch
    push:
      branches: ["doctum-test"]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        name: Update-DoctumDocs-Branch

        steps:
          - uses: actions/checkout@v3
            with:
              # The branch, tag or SHA to checkout. When checking out the repository that
              # triggered a workflow, this defaults to the reference or SHA for that event.
              # Otherwise, uses the default branch.
              ref: 'doctum-test'
        
          - name: build doctum docs
            uses: sudo-bot/action-doctum@latest
            with:
                config-file: doctum-config.php
                # parse, render or update
                method: "update"
                # (optional) defaults to '--output-format=github --no-ansi --no-progress -v'
                cli-args: "--output-format=github --no-ansi --no-progress -v"

          - name: Remove Unrequired Items
            run: | 
                rm -rf config
                rm -rf database
                rm -rf resources
                rm -rf public
                rm -rf tests
                rm codecov.yml
                rm coverage.xml
                rm phpstan.neon
                rm phpunit.xml.dist
                rm psalm.xml.dist
                rm -rf cache
                rm -rf build/cache

          - name: Git Remove
            run: |
              git rm cache
              git rm build/cache

          - name: Git Add
            run: |
                git add docs/*
                git add build/*

          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
                # Optional. Commit message for the created commit.
                # Defaults to "Apply automatic changes"
                commit_message: Automated Change

                # Optional. Options used by `git-commit`.
                # See https://git-scm.com/docs/git-commit#_options
                commit_options: '--no-verify --signoff'

                # Optional. Option used by `git-status` to determine if the repository is 
                # dirty. See https://git-scm.com/docs/git-status#_options
                status_options: '--untracked-files=yes'

                # Optional. Local and remote branch name where commit is going to be pushed
                #  to. Defaults to the current branch.
                #  You might need to set `create_branch: true` if the branch does not exist.
                branch: doctum-docs-newest-2

                # Optional. Options used by `git-add`.
                # See https://git-scm.com/docs/git-add#_options
                add_options: '-u'

                # Optional. Disable dirty check and always try to create a commit and push
                skip_dirty_check: true 

                # Optional. Skip internal call to `git fetch`
                skip_fetch: true    
                
                # Optional. Skip internal call to `git checkout`
                skip_checkout: true

                # Optional. Options used by `git-push`.
                # See https://git-scm.com/docs/git-push#_options
                push_options: '--force'

                # Optional commit user and author settings
                commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
                commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
                commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
                create_branch: true
