name: run-tests-doctum

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        laravel: [10]
        stability: [prefer-dist]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
        - uses: actions/checkout@v4

        - name: build doctum docs
          uses: sudo-bot/action-doctum@v5
          with:
              config-file: doctum-config.php
              # parse, render or update
              method: "update"
              # (optional) defaults to '--output-format=github --no-ansi --no-progress -v'
              cli-args: "--output-format=github --no-ansi --no-progress -v"

        - name: Remove Unrelated Files
          run: |
            rm -rf database
            rm -rf config
            rm -rf docs
            rm -rf public
            rm -rf resources
            rm -rf src
            rm -rf tests

        - name: Move New Docs To docs
          run: |
            cp -R ./doctum/build docs
      
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            # Optional. Commit message for the created commit.
            # Defaults to "Apply automatic changes"
            commit_message: Automated Change

            # Optional. Options used by `git-commit`.
            # See https://git-scm.com/docs/git-commit#_options
            commit_options: '--no-verify --signoff'

            # Optional. Option used by `git-status` to determine if the repository is 
            # dirty. See https://git-scm.com/docs/git-status#_options
            status_options: '--untracked-files=yes'

            # Optional. Local and remote branch name where commit is going to be pushed
            #  to. Defaults to the current branch.
            #  You might need to set `create_branch: true` if the branch does not exist.
            branch: doctum-docs-new2

            # Optional. Options used by `git-add`.
            # See https://git-scm.com/docs/git-add#_options
            add_options: '-u'

            # Optional. Disable dirty check and always try to create a commit and push
            skip_dirty_check: true 

            # Optional. Skip internal call to `git fetch`
            skip_fetch: true    
            
            # Optional. Skip internal call to `git checkout`
            skip_checkout: true

            # Optional. Options used by `git-push`.
            # See https://git-scm.com/docs/git-push#_options
            push_options: '--force'

            # Optional commit user and author settings
            commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
            commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
            commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
            create_branch: true