name: run-tests-doctum

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        laravel: [10]
        stability: [prefer-dist]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
        - uses: actions/checkout@v4
        - name: build doctum docs
          uses: sudo-bot/action-doctum@v5
          with:
              config-file: doctum-config.php
              # parse, render or update
              method: "update"
              # (optional) defaults to '--output-format=github --no-ansi --no-progress -v'
              cli-args: "--output-format=github --no-ansi --no-progress -v"
      
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Add Doctum Output